; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-n16r8]
platform = espressif32@6.8.1
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.memory_type = qio_opi
board_build.flash_size = 16MB
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
board_upload.flash_size = 16MB
build_flags = 
	-D BOARD_HAS_PSRAM
	-D CONFIG_SPIRAM_CACHE_WORKAROUND
	-D ARDUINO_USB_CDC_ON_BOOT=0
	-D CORE_DEBUG_LEVEL=2
monitor_speed = 115200
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0
upload_speed = 921600
extra_scripts = pre:tools/embed_html.py
lib_deps = esp32async/ESPAsyncWebServer@^3.7.2
lib_ignore = ESPAsyncTCP, RPAsyncTCP
